### ISSUE TITLE
Dynamic types instead of colors - analyzer conflict?

### ISSUE THREAD

**Issue by obiwanzenobi** [pro100andrey/theme_extensions_builder#10]
Builder generates 
```dart
 @override
  ThemeExtension<AppColors> copyWith({
    dynamic primary,
    dynamic secondary,
    dynamic orangeMedium,
    dynamic orangeLight,
```

from 
```dart
  final Color primary;
  final Color secondary;
  final Color orangeMedium;
  final Color orangeLight;
```

project uses analyzer: 5.2.0 and build_runner: 2.3.3

**Comment by pro100andrey** [comment]
Hi @obiwanzenobi, Could you provide minimal example for reproduce?

Thanks

**Comment by pro100andrey** [comment]
Hi @obiwanzenobi any updates?

Thanks!

**Comment by obiwanzenobi** [comment]
Hi, 
Problems were caused by coexisting analyzer 4.x and 5.2.0. It could happen right after updating dependencies (including analyzer). Then non literal types are not properly detected because of version mismatch. 
Flutter clean, pub build_runner clean, removing pubspec.lock and flutter pub get again solves the problem.

**Comment by pro100andrey** [comment]
> or maybe setting analyzer version to 5.2 - 6.0 instead of 4.6 - 6.0 could prevent such case 🤔

I will check later it, 

Thanks!
