### ISSUE TITLE
Analyser Dependency conflict with flutter_bloc, Unique output file for the generated part file.

### ISSUE THREAD

**Issue by Vidhyadharan-matchmove** [pro100andrey/theme_extensions_builder#2]
1. The analyser dependency is restricted to >=5.10 to <5.3.0 this is too restrictive and results in a conflict with flutter_bloc which has analyser dependency of <5.0.0, i had downgraded the analyser dependency to ^4.7.0 and did face any issues. This could me downgraded to improve compatibility of the library.
2. The generated part file needs to be unique the library generates part file with `.g.dart` extension, this conflicts with `json_serializable` which also generates the part file with the same name. If this generated part file is renamed to `.gte.dart` it will fix the unique output issue reported by `build_runner`.

Thanks for the very helpful library.

**Comment by pro100andrey** [comment]
Hi @Vidhyadharan-matchmove, I need some time for investigating

Thank you!

**Comment by pro100andrey** [comment]
@Vidhyadharan-matchmove 
Fixed in `theme_extensions_builder: ^2.0.0`

Thanks !

**Comment by Vidhyadharan-matchmove** [comment]
Thanks for the quick response, Stay safe.

**Comment by Vidhyadharan-matchmove** [comment]
@pro100andrey the annotation dependency from theme_builder_extension pubspec.yaml needs to updated to 2.0.0 else i'm getting the following error.

Because no versions of theme_extensions_builder match >2.0.0 <3.0.0 and theme_extensions_builder 2.0.0 depends on theme_extensions_builder_annotation ^1.0.0+1, theme_extensions_builder ^2.0.0 requires theme_extensions_builder_annotation ^1.0.0+1.

**Comment by pro100andrey** [comment]
@Vidhyadharan-matchmove Sorry, fixed in theme_extensions_builder: ^2.0.1

Thanks!

**Comment by Vidhyadharan-matchmove** [comment]
Great. Thanks, Stay Safe.
